export const logo =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j0p8AAAAASUVORK5CYII=';
export function fixture(patch = {}) {
  return {
    schemaVersion: 1,
    kind: 'invoice',
    reference: 'ASTER-2026-001',
    agency: {
      name: 'Aster Studio',
      legalName: 'Aster Studio — owner testing',
      address: 'Test studio address\nDhaka, Bangladesh',
      email: 'studio@example.test',
      website: 'example.test',
      logoDataUrl: '',
      accentColor: '#27695d',
    },
    client: {
      name: 'Harbor Studio',
      contact: 'Project contact',
      email: 'client@example.test',
      address: 'Client billing address',
    },
    projectName: 'Harbor / Website',
    changeTitle: 'Add a journal CMS collection',
    changeReference: 'Change 01',
    revision: 1,
    status: 'Approved',
    currency: 'USD',
    issueDate: '2026-10-01',
    dueDate: '2026-10-15',
    scope: 'A separate journal collection and reusable article template.',
    deliverables: 'One journal collection, article template and listing page.',
    removedScope: '',
    exclusions: 'Copywriting and bulk content entry.',
    dependencies: 'Client supplies approved copy and images.',
    assumptions: 'Reuse the approved design system.',
    deliveryImplications: 'Schedule follows receipt of approved content.',
    approvalText: 'The existing agreement remains in force.',
    approvalRecorded: 'Client accepted the defined scope and fee by email.',
    approvalDate: '2026-10-01',
    description: 'Approved journal collection and templates.',
    subtotal: '800.00',
    taxRate: '5.00',
    tax: '40.00',
    total: '840.00',
    paymentInstructions: 'Owner test fixture: no real payment requested.',
    footer: 'Prepared from a preserved revision. Manual payment tracking.',
    demo: false,
    ...patch,
  };
}
